from pathlib import Path
from typing import Dict, List, Optional, Set

from Utils.utils import read_config, time_stamp, extract_vcf_samples


class CV_preparation:
    @staticmethod
    def read_samples_file(samples_path: Path) -> List[str]:
        with open(samples_path, "r") as f:
            raw = [ln.strip() for ln in f if ln.strip()]
        if len(raw) == 1 and "," in raw[0]:
            return [x.strip() for x in raw[0].split(",") if x.strip()]
        return raw

    @staticmethod
    def write_samples_file(samples_path: Path, samples: List[str]) -> None:
        samples_path.parent.mkdir(parents=True, exist_ok=True)
        with open(samples_path, "w") as f:
            for sample in samples:
                f.write(f"{sample}\n")

    @staticmethod
    def write_cv_config_readme(cv_config_dir: Path) -> None:
        readme_path = cv_config_dir / "README.txt"
        content = "\n".join(
            [
                "CV config directory for prediction steps (generated by run_prediction_pipeline.py).",
                "",
                "Files:",
                "- fold_<id>_config.txt: key=value settings for a single CV fold.",
                "  Required keys: config_file, file_fold_index, train_samples_file, test_samples_file.",
                "  Optional keys: gwas_pcs, pca_n_components, top_n_snps, models.",
                "- fold_<id>_train_samples.txt: one sample ID per line for GWAS (train split).",
                "- fold_<id>_test_samples.txt: one sample ID per line for model prep (test split).",
                "",
                "Notes:",
                "- Step 4 uses train samples to run GWAS per fold.",
                "- Step 5 uses train samples for PRS scoring.",
                "- Step 6 uses test samples for model prep and training.",
            ]
        )
        with open(readme_path, "w") as f:
            f.write(content + "\n")

    @staticmethod
    def parse_optional_int(raw: Optional[str]) -> Optional[int]:
        if raw is None:
            return None
        s = str(raw).strip()
        if not s:
            return None
        return int(s)

    @staticmethod
    def write_cv_folds(
        path: Path,
        fold_samples: List[Dict[str, object]],
        metadata: Optional[Dict[str, str]] = None,
    ) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            if metadata:
                for key, val in metadata.items():
                    f.write(f"#{key}={val}\n")
            for rec in fold_samples:
                fold_id = rec["fold_id"]
                for s in rec["train_samples"]:
                    f.write(f"{fold_id}\ttrain\t{s}\n")
                for s in rec["test_samples"]:
                    f.write(f"{fold_id}\ttest\t{s}\n")

    @staticmethod
    def read_cv_folds(path: Path, common: Set[str]) -> List[Dict[str, object]]:
        fold_map: Dict[str, Dict[str, List[str]]] = {}
        fold_order: List[str] = []
        bad_samples: Set[str] = set()
        with open(path, "r") as f:
            for raw in f:
                line = raw.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) != 3:
                    continue
                fold_id, split, sample = parts
                if split not in {"train", "test"}:
                    raise ValueError(f"Invalid split label in {path}: {split}")
                if sample not in common:
                    bad_samples.add(sample)
                    continue
                if fold_id not in fold_map:
                    fold_map[fold_id] = {"train": [], "test": []}
                    fold_order.append(fold_id)
                fold_map[fold_id][split].append(sample)

        if bad_samples:
            preview = ", ".join(sorted(list(bad_samples))[:10])
            suffix = " ..." if len(bad_samples) > 10 else ""
            raise ValueError(f"Fold file contains samples not in current data: {preview}{suffix}")

        fold_samples: List[Dict[str, object]] = []
        for fold_id in fold_order:
            rec = fold_map[fold_id]
            if not rec["train"] or not rec["test"]:
                raise ValueError(f"Incomplete fold in {path}: {fold_id}")
            fold_samples.append(
                {
                    "fold_id": fold_id,
                    "train_samples": rec["train"],
                    "test_samples": rec["test"],
                }
            )
        return fold_samples

    @staticmethod
    def read_fold_config(path: Path) -> Dict[str, str]:
        cfg = read_config(path)
        required = ["config_file", "file_fold_index", "train_samples_file", "test_samples_file"]
        missing = [k for k in required if not cfg.get(k)]
        if missing:
            missing_str = ", ".join(missing)
            raise ValueError(f"Fold config missing required keys in {path}: {missing_str}")

        for key in ("config_file", "train_samples_file", "test_samples_file"):
            candidate = Path(cfg[key]).expanduser()
            if not candidate.exists():
                raise FileNotFoundError(f"Fold config file missing: {candidate}")
        return cfg

    @staticmethod
    def write_cv_fold_configs(
        cfg_path: Path,
        fold_samples: List[Dict[str, object]],
        cv_config_dir: Path,
        gwas_pcs: str,
        pca_n_components: Optional[str],
        top_n_snps: str,
        models: str,
    ) -> List[Path]:
        cv_config_dir.mkdir(parents=True, exist_ok=True)
        CV_preparation.write_cv_config_readme(cv_config_dir)
        cfg_path = cfg_path.expanduser().resolve()
        fold_config_paths: List[Path] = []
        for rec in fold_samples:
            fold_id = str(rec["fold_id"])
            train_path = cv_config_dir / f"fold_{fold_id}_train_samples.txt"
            test_path = cv_config_dir / f"fold_{fold_id}_test_samples.txt"
            CV_preparation.write_samples_file(train_path, list(rec["train_samples"]))
            CV_preparation.write_samples_file(test_path, list(rec["test_samples"]))

            fold_cfg_path = cv_config_dir / f"fold_{fold_id}_config.txt"
            with open(fold_cfg_path, "w") as f:
                f.write(f"config_file={cfg_path}\n")
                f.write(f"file_fold_index={fold_id}\n")
                f.write(f"train_samples_file={train_path}\n")
                f.write(f"test_samples_file={test_path}\n")
                if gwas_pcs:
                    f.write(f"gwas_pcs={gwas_pcs}\n")
                if pca_n_components:
                    f.write(f"pca_n_components={pca_n_components}\n")
                if top_n_snps:
                    f.write(f"top_n_snps={top_n_snps}\n")
                if models:
                    f.write(f"models={models}\n")
            fold_config_paths.append(fold_cfg_path)
        return fold_config_paths

    @staticmethod
    def prepare_cv_fold_configs(
        *,
        cfg_path: Path,
        vcf_path: Path,
        pheno_path: Path,
        pheno_col: str,
        data_type: str,
        num_splits: int,
        random_state: int,
        cv_folds_file: Path,
        cv_config_dir: Path,
        gwas_pcs: str,
        pca_n_components: Optional[str],
        top_n_snps: str,
        models: str,
        create_if_missing: bool,
    ) -> List[Path]:
        import numpy as np
        import pandas as pd
        from sklearn.model_selection import KFold, StratifiedKFold

        pheno = pd.read_csv(pheno_path, sep=None, engine="python")
        if "taxa" not in pheno.columns:
            raise ValueError("phenotype_csv_path must contain a 'taxa' column.")
        if pheno_col not in pheno.columns:
            raise ValueError(f"phenotype column not found: {pheno_col}")

        pheno = pheno[["taxa", pheno_col]].dropna()
        pheno = pheno.set_index("taxa")

        vcf_samples = extract_vcf_samples(vcf_path)
        common = [s for s in vcf_samples if s in pheno.index]
        if not common:
            raise ValueError("No overlapping samples between VCF and phenotype CSV.")

        if cv_folds_file.exists():
            fold_samples = CV_preparation.read_cv_folds(cv_folds_file, set(common))
            time_stamp(f"[cv] Using existing CV folds: {cv_folds_file}")
        else:
            if not create_if_missing:
                raise FileNotFoundError(
                    f"cv_folds_file not found: {cv_folds_file} (run step 4 to generate CV folds)"
                )

            random_state = int(random_state)
            n_splits = max(2, int(num_splits))
            y = pheno.loc[common, pheno_col].values

            if data_type == "regression":
                splitter = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
            else:
                splitter = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)

            fold_samples = []
            fold_counter = 0
            for train_idx, test_idx in splitter.split(np.zeros(len(common)), y):
                fold_counter += 1
                fold_index = fold_counter
                file_fold_index = f"{fold_index}"
                train_samples = [common[i] for i in train_idx]
                test_samples = [common[i] for i in test_idx]
                fold_samples.append(
                    {
                        "fold_id": file_fold_index,
                        "train_samples": train_samples,
                        "test_samples": test_samples,
                    }
                )

            CV_preparation.write_cv_folds(
                cv_folds_file,
                fold_samples,
                metadata={
                    "n_splits": str(n_splits),
                    "random_state": str(random_state),
                    "data_type": str(data_type),
                    "samples": str(len(common)),
                },
            )
            time_stamp(f"[cv] Wrote CV folds: {cv_folds_file}")

        fold_configs = CV_preparation.write_cv_fold_configs(
            cfg_path=cfg_path,
            fold_samples=fold_samples,
            cv_config_dir=cv_config_dir,
            gwas_pcs=gwas_pcs,
            pca_n_components=pca_n_components,
            top_n_snps=top_n_snps,
            models=models,
        )
        time_stamp(f"[cv] Wrote fold configs: {cv_config_dir} ({len(fold_configs)} folds)")
        return fold_configs
